version: "3.9"
services:
  chat-api:
    build: stocks-chat-api
    ports:
      - 3000:3000
    environment:
      HOST: :3000
      POSTGRES_CONN: postgres://postgres:postgres@postgres:5432/postgres?user=postgres&password=secret&sslmode=disable
      JWT_SECRET: secr3t
      RABBIT_MQ_CONN: amqp://guest:guest@rabbitmq:5672
      IS_DEV: true
    depends_on:
      - postgres
      - rabbitmq

  bot-worker:
    build: 
      context: ./stocks-chatbot
      dockerfile: dockerfile
    environment:
      POSTGRES_CONN: postgres://postgres:postgres@postgres:5432/postgres?user=postgres&password=secret&sslmode=disable
      RABBIT_MQ_CONN: amqp://guest:guest@rabbitmq:5672
      IS_DEV: true
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
