FROM golang:1.18 as builder

WORKDIR /go/src/app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o worker  cmd/worker/main.go


FROM ubuntu:22.04

RUN apt-get update -y
RUN apt-get install curl -y

WORKDIR /app/

COPY --from=builder /go/src/app/worker .

RUN useradd --create-home --uid 1000 gopher
USER 1000

CMD ./worker
