run:
  allow-parallel-runners: true
  go: '1.18'
    
linters-settings:
  gofumpt:
    lang-version: "1.18"
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake

linters:
  enable-all: true
  fast: true
  disable:
    - scopelint
    - ifshort
    - nosnakecase
    - gci
    - goimports

