FROM node:18 as build

WORKDIR app/

COPY ./package.json .
COPY ./package-lock.json .

RUN npm install && mv node_modules ../

COPY . .

RUN npm run build

FROM nginx:1.23

COPY --from=build /app/dist /app/
COPY ./nginx.conf /etc/nginx/nginx.conf

RUN mkdir /etc/nginx/logs
RUN touch /etc/nginx/logs/error.log
